language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q . --use-mirrors
script:
  - python manage.py test
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change